properties([
    parameters([
        choice(choices: ['dev', 'qa'], description: 'Choose Environment', name: 'environment')
    ])
])
def aws_region_var = ''
if(params.environment == "dev") {
    println("Creating image at Dev")
    aws_region_var = "us-east-1"
}
else if(params.environment == "qa") {
    println("Creating image at QA")
    aws_region_var = "us-east-2"
}
 
def image_name = "asg-image-${params.environment}-${ UUID.randomUUID().toString()}"
node{
    stage('Pull Repo') {
        git branch: 'dev', url: 'https://github.com/shamal112mn/demo-aws-cicd.git'
    }
    withCredentials([usernamePassword(credentialsId: 'jenkins_aws_keys', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
        withEnv(["AWS_REGION=${aws_region_var}", "PACKER_AMI_NAME=${image_name}"]) {
            stage('Packer Validate') {
                sh """
                    cd packer
                    packer version
                    packer validate packertest.json
                    cat text.txt
                """
            }
            stage('Packer Build') {
                sh """
                    cd packer
                    packer build packertest.json
                """
            }
        }
    }
}